services:
  yarp-gateway:
    image: yarp-gateway
    build:
      context: .
      dockerfile: YarpApiGateWay/Dockerfile
    container_name: yarp-gateway
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=NotificationDb;Username=postgres;Password=yourpassword
    depends_on:
      - customer-profile
      - account-services
    networks:
      - banking-network

  customer-profile:
    image: customer-profile
    build:
      context: .
      dockerfile: CustomerProfile/Dockerfile
    container_name: customer-profile
    ports:
      - "5039:8080"
      - "7146:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=CustomerDb;Username=postgres;Password=yourpassword
      - Kafka__BootstrapServers=kafka:9092
      - Redis__ConnectionString=redis:6379
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - banking-network

  account-services:
    image: account-services
    build:
      context: .
      dockerfile: AccountServices/Dockerfile
    container_name: account-services
    ports:
      - "5167:8080"
      - "7248:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AccountDb;Username=postgres;Password=yourpassword
      - Kafka__BootstrapServers=kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - banking-network

  transaction-service:
    image: transaction-service
    build:
      context: .
      dockerfile: TransactionService/Dockerfile
    container_name: transaction-service
    ports:
      - "5238:8080"
      - "7217:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=TransactionDb;Username=postgres;Password=yourpassword
      - Kafka__BootstrapServers=kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - banking-network

  notification-service:
    image: notification-service
    build:
      context: .
      dockerfile: Notification/Dockerfile
    container_name: notification-service
    ports:
      - "5049:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Kafka__BootstrapServers=kafka:9092
      - EmailOptions__SmtpHost=smtp.example.com
      - EmailOptions__SmtpPort=587
    depends_on:
      - kafka
    networks:
      - banking-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - banking-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - banking-network

  kafka:
    image: apache/kafka:4.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  postgres-data:
